# Universal Service Template

apiVersion: v1
kind: Service
metadata:
  name: text-service
  namespace: production
  labels:
    app: text-service
    owner: backend-team
    managed-by: canvas-engine
    # Standard label for monitoring tools to auto-discover services
    monitor: "true"
  annotations:
    # Annotations for internal load balancers (if needed in future)
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  # ClusterIP is correct for internal services behind an Ingress
  type: ClusterIP
  selector:
    app: text-service
  ports:
    - name: http-api
      port: 80                  # The stable port other services call
      targetPort: 8000 # The actual port your container listens on (8000)
      protocol: TCP